cocoders_console_command:
    resource: "@CocodersConsoleCommandBundle/Resources/config/routing.xml"
    prefix:   /

cocoders_core:
    resource: "@CocodersCoreBundle/Resources/config/routing.xml"
    prefix:   /

